# 対象ファイル名
input_file: "beyblade_parts.txt"

# 区分
div_list: [
    "レイヤー", 
    "ガチンコチップ", 
    "ウエイト", 
    "ベース", 
    "ディスク", 
    "フレーム", 
    "ドライバー"
    ]

# IDの頭文字
id_initial: 
    レイヤー: "LY" 
    ガチンコチップ: "GC"  
    ウエイト: "GW"
    ベース: "GB"
    ディスク: "DS"
    コアディスク: "CD"
    フレーム: "FL"
    ドライバー: "Dr"

# タイプ
type_list: [
    "アタック", 
    "バランス", 
    "スタミナ", 
    "ディフェンス"
    ]

# コアディスク
core_list: [
    "シックス", 
    "ツー", 
    "フォー", 
    "エイト", 
    "セブン", 
    "ファイブ", 
    "ワン", 
    "ゼロ", 
    "スリー", 
    "トゥエルブ", 
    "イレブン", 
    "サーティーン", 
    "テン", 
    "ワンダッシュ", 
    "エイトダッシュ", 
    "ダブルオー", 
    ]